# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_similarity_kmer <- function(x, k, total_kmer) {
    .Call('_Bobro_calc_similarity_kmer', PACKAGE = 'Bobro', x, k, total_kmer)
}

calc2 <- function(x, k, total_kmer) {
    .Call('_Bobro_calc2', PACKAGE = 'Bobro', x, k, total_kmer)
}

